### ISSUE TITLE
null value for unused argument in spec

### ISSUE THREAD

**Issue by bregman-arie** [rhosqeauto/InfraRed#151]
I added new arguent in .spec file:

```yaml
       - title: key_name
         options:
               key_name:
                   type: Value
                   help: The name of the key
```
When running ir-provision with the argument (like ir-provision openstack --image rhel-7.2) I still see the variable in the generated settings:

key_name: null

I would expect it to not be included in the settings at all. It makes it easier for us to check if the variable defined in Ansible tasks.
